import { useMemo, useState } from "react";
import VolumeBarChart from "../charts/VolumeBarChart";
import WeightLineChart from "../charts/WeightLineChart";
import { useAppState } from "../../store/globalState";

function SegmentTabs({ items, active, onChange }) {
  return <div className="no-scrollbar flex gap-2 overflow-x-auto rounded-full border border-white/10 bg-white/5 p-1">{items.map((item) => <button key={item.id} type="button" onClick={() => onChange(item.id)} className={`rounded-full px-4 py-2 text-sm font-semibold ${active === item.id ? "bg-orange text-white" : "text-text2"}`}>{item.label}</button>)}</div>;
}

export default function RanksTab({ profile, workouts, galleryEntries, onSaveExerciseRank }) {
  const { subTabs, setSubTab } = useAppState();
  const activeTab = subTabs.ranks;
  const [calculator, setCalculator] = useState({ exercise: "Bench Press", weight: 80, reps: 8 });
  const rankSeries = workouts.slice(0, 8).reverse().map((_, index) => 48 + index * 5);
  const labels = workouts.slice(0, 8).reverse().map((workout) => new Date(workout.completed_at).toLocaleDateString(undefined, { month: "short", day: "numeric" }));
  const calculatedLp = Math.round(Number(calculator.weight) * 2.6 + Number(calculator.reps) * 15);
  const calculatedTier = calculatedLp > 620 ? "OLYMPIAN" : calculatedLp > 520 ? "DIAMOND II" : calculatedLp > 420 ? "TITAN II" : "PIONEER";
  const groupedMuscles = useMemo(() => ([ ["Arms", "3/3 Complete"], ["Legs", "4/6 Complete"], ["Core", "0/2 Complete"], ["Shoulders", "2/3 Complete"], ["Chest", "2/2 Complete"], ["Back", "4/4 Complete"] ]), []);

  return (
    <div className="space-y-5">
      <SegmentTabs items={[{ id: "yourRank", label: "Your Rank" }, { id: "bodygraph", label: "Bodygraph" }, { id: "leagues", label: "Leagues" }, { id: "gallery", label: "Gallery" }, { id: "calculator", label: "Calculator" }, { id: "analysis", label: "Analysis" }]} active={activeTab} onChange={(next) => setSubTab("ranks", next)} />

      {activeTab === "yourRank" && (
        <div className="space-y-5"><section className="rounded-[28px] border border-purple/25 bg-[linear-gradient(135deg,#2d2155_0%,#120f1d_100%)] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.28em] text-purple">Crystalline momentum</p><h2 className="mt-2 text-3xl font-bold text-text">DIAMOND II • 78 LP</h2><p className="mt-2 text-sm text-text2">Keep stacking high-quality sessions.</p></div><button type="button" onClick={() => window.alert("Rank card copied for sharing.")} className="rounded-full border border-white/10 px-4 py-2 text-sm text-text2">Share</button></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-[22px] border border-white/8 bg-[#090912] p-4"><p className="text-xs uppercase tracking-[0.24em] text-text3">Global</p><p className="mt-2 text-xl font-bold text-text">#45166</p><p className="text-sm text-green">Top 17.3% • 41800 ?</p></div><div className="rounded-[22px] border border-white/8 bg-[#090912] p-4"><p className="text-xs uppercase tracking-[0.24em] text-text3">Regional</p><p className="mt-2 text-xl font-bold text-text">Diamond</p><p className="text-sm text-purple">South Asia</p></div></div></section><section className="rounded-[24px] border border-white/10 bg-card p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.24em] text-text3">Rank overtime</p><h3 className="mt-2 text-xl font-bold text-text">One month climb</h3></div><div className="rounded-full border border-white/10 px-4 py-2 text-sm text-text2">1M</div></div><div className="chart-shell"><WeightLineChart labels={labels} values={rankSeries} /></div></section></div>
      )}

      {activeTab === "bodygraph" && (
        <div className="space-y-5"><section className="rounded-[24px] border border-blue/20 bg-card p-5"><div className="grid grid-cols-2 gap-3">{["Front", "Back"].map((label) => (<div key={label} className="rounded-[22px] border border-white/8 bg-[#090912] p-4 text-center"><div className="mx-auto h-44 w-28 rounded-[999px] border border-blue/25 bg-[radial-gradient(circle_at_center,rgba(0,191,255,0.25),transparent_70%)]" /><p className="mt-3 text-xs uppercase tracking-[0.24em] text-text3">{label}</p></div>))}</div><div className="mt-4 rounded-[24px] border border-blue/20 bg-blue/10 p-4"><p className="text-xs uppercase tracking-[0.24em] text-blue">Last workout</p><h3 className="mt-2 text-xl font-bold text-text">You improved 15 muscle groups!</h3><button type="button" onClick={() => window.alert("Improvement breakdown opens here.")} className="mt-3 rounded-full bg-blue px-4 py-2 text-sm font-bold text-[#03131d]">SEE IMPROVEMENTS</button></div></section><section className="space-y-3">{groupedMuscles.map(([group, completion]) => (<div key={group} className="rounded-[22px] border border-white/10 bg-card p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue/10 text-blue">?</div><div><p className="font-semibold text-text">{group}</p><p className="text-sm text-text3">{completion}</p></div></div><button type="button" onClick={() => window.alert(`${group} detail coming from live ranking data.`)} className="text-text2">?</button></div></div>))}</section></div>
      )}

      {activeTab === "leagues" && <section className="rounded-[24px] border border-white/10 bg-card p-6 text-center"><div className="mx-auto flex h-28 w-28 items-center justify-center rounded-[28px] border border-white/10 bg-[conic-gradient(from_180deg,#00BFFF,#A78BFA,#FFD700,#00BFFF)] text-4xl">?</div><h3 className="mt-4 text-2xl font-bold text-text">You&apos;re in queue</h3><p className="mt-2 text-sm text-text2">Wait for the next league reset to get in with your Liftoff Rank.</p><button type="button" onClick={() => window.alert("League countdown is synced to the next reset window.")} className="mt-5 rounded-full bg-blue px-5 py-3 text-sm font-bold text-[#03131d]">3 Days</button></section>}

      {activeTab === "gallery" && <div className="space-y-4">{galleryEntries.map((entry) => (<article key={entry.id} className={`rounded-[24px] border p-5 ${entry.tier.includes("OLYMPIAN") ? "border-gold/25 bg-gradient-to-br from-gold/20 to-card" : "border-red/20 bg-gradient-to-br from-red/15 to-card"}`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.24em] text-text3">{entry.tier}</p><h3 className="mt-2 text-xl font-bold text-text">{entry.exercise_name}</h3><p className="mt-1 text-sm text-text2">{entry.lp} LP</p></div><div className="rounded-2xl border border-white/10 bg-[#090912] px-3 py-2 text-lg">?</div></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="rounded-2xl border border-white/10 bg-white/5 p-3"><span className="mb-2 block text-xs uppercase tracking-[0.24em] text-text3">KG</span><input type="number" value={entry.weight_kg} onChange={(event) => onSaveExerciseRank({ ...entry, weight_kg: Number(event.target.value) })} className="w-full bg-transparent text-xl font-bold text-text outline-none" /></label><label className="rounded-2xl border border-white/10 bg-white/5 p-3"><span className="mb-2 block text-xs uppercase tracking-[0.24em] text-text3">Reps</span><input type="number" value={entry.reps} onChange={(event) => onSaveExerciseRank({ ...entry, reps: Number(event.target.value) })} className="w-full bg-transparent text-xl font-bold text-text outline-none" /></label></div></article>))}</div>}

      {activeTab === "calculator" && <section className="rounded-[24px] border border-white/10 bg-card p-5"><div className="grid gap-4 sm:grid-cols-3"><label className="rounded-2xl border border-white/10 bg-white/5 p-4"><span className="mb-2 block text-xs uppercase tracking-[0.24em] text-text3">Exercise</span><input value={calculator.exercise} onChange={(event) => setCalculator((current) => ({ ...current, exercise: event.target.value }))} className="w-full bg-transparent text-text outline-none" /></label><label className="rounded-2xl border border-white/10 bg-white/5 p-4"><span className="mb-2 block text-xs uppercase tracking-[0.24em] text-text3">Weight</span><input type="number" value={calculator.weight} onChange={(event) => setCalculator((current) => ({ ...current, weight: Number(event.target.value) }))} className="w-full bg-transparent text-text outline-none" /></label><label className="rounded-2xl border border-white/10 bg-white/5 p-4"><span className="mb-2 block text-xs uppercase tracking-[0.24em] text-text3">Reps</span><input type="number" value={calculator.reps} onChange={(event) => setCalculator((current) => ({ ...current, reps: Number(event.target.value) }))} className="w-full bg-transparent text-text outline-none" /></label></div><div className="mt-5 rounded-[24px] border border-blue/20 bg-blue/10 p-5"><p className="text-xs uppercase tracking-[0.24em] text-blue">Calculated Rank</p><h3 className="mt-2 text-2xl font-bold text-text">{calculatedTier}</h3><p className="mt-2 text-sm text-text2">{calculator.exercise} ? {calculatedLp} LP</p></div></section>}

      {activeTab === "analysis" && <div className="space-y-5"><section className="rounded-[24px] border border-white/10 bg-card p-5"><p className="text-xs uppercase tracking-[0.24em] text-text3">Workout heatmap</p><h3 className="mt-2 text-xl font-bold text-text">Last 12 weeks</h3><div className="mt-4 grid grid-cols-7 gap-2">{Array.from({ length: 84 }).map((_, index) => (<div key={index} className={`aspect-square rounded-md ${index % 4 === 0 ? "bg-blue/30" : index % 6 === 0 ? "bg-orange/25" : "bg-white/5"}`} />))}</div></section><section className="rounded-[24px] border border-white/10 bg-card p-5"><p className="text-xs uppercase tracking-[0.24em] text-text3">Volume trend</p><div className="chart-shell mt-4"><VolumeBarChart labels={labels} values={workouts.slice(0, 8).reverse().map((entry) => Number(entry.volume_kg ?? 0))} color="#FF6B35" /></div></section><section className="rounded-[24px] border border-white/10 bg-card p-5"><p className="text-xs uppercase tracking-[0.24em] text-text3">Top improvements</p><div className="mt-4 space-y-3">{galleryEntries.slice(0, 3).map((entry) => (<div key={entry.id} className="rounded-2xl border border-white/8 bg-[#090912] p-4"><div className="flex items-center justify-between"><p className="font-semibold text-text">{entry.exercise_name}</p><p className="font-mono text-blue">{entry.lp} LP</p></div></div>))}</div></section></div>}
    </div>
  );
}

